name: Angular Package

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Project
        run: ng build ngx-custom-carousel
      - name: Publish to GitHub Packages
        working-directory: dist/dist/ngx-custom-carousel
        run:
          npm publish --access public --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
        


