name: Angular Package

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Project
        run: ng build ngx-custom-carousel

      - name: Setup working direcotry
        run: cd dist/ngx-custom-carousel

      - name: Publish the library
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          package: package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}



