name: Angular Package

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Project
        run: ng build ngx-custom-carousel
      - name: Publish to GitHub Packages
        run: |
          cd dist/ngx-custom-carousel
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
